# SERVER API CONFIGS
api_key: INPUT YOUR API KEY HERE!
api_url: http://129.152.27.36/assistant/api.php
api_up: http://129.152.27.36/assistant/api_uploads

# MODELS INSTALLED
models: [
    franciscomvargas/neuralqa/qa,
    franciscomvargas/neuralqa/expansion,
    franciscomvargas/descraper/url,
    franciscomvargas/descraper/html
]

## Task Method: Static OBJ
task_to_method: {
    question-answering-large-dataset: run_neuralqa_qa,  # franciscomvargas/neuralqa/qa
    query-expansion: run_neuralqa_expansion,            # franciscomvargas/neuralqa/expansion
    url-to-text: run_descraper_url,                     # franciscomvargas/descraper/url
    html-to-text: run_descraper_html                    # franciscomvargas/descraper/html
}