# SERVER API CONFIGS
api_key: INPUT YOUR API KEY HERE!
api_url: http://129.152.27.36/assistant/api.php
api_up: http://129.152.27.36/assistant/api_uploads

# MODELS INSTALLED
models: [
    franciscomvargas/neuralqa/qa,
    franciscomvargas/neuralqa/expansion,
    franciscomvargas/descraper/url,
    franciscomvargas/descraper/html
]

## Model Method: Static OBJ
model_to_method: {
    franciscomvargas/neuralqa/qa: run_neuralqa_qa,
    franciscomvargas/neuralqa/expansion: run_neuralqa_expansion,
    franciscomvargas/descraper/url: run_descraper_url,
    franciscomvargas/descraper/html: run_descraper_html
}