## DeSOTA Services Params
services_params: {
    # DeSOTA Required Tools
    desotaai/derunner: {
        win: {
            version: 0.1.0,
            commit: aa5dcb3966da04cfae39ac05cd83c70c37d17fbd,
            project_dir: Desota\DeRunner,
            execs_path: executables\Windows,
            setup: derunner.setup.bat,
            setup_args: [/manualstart],
            uninstaller: derunner.uninstall.bat,
            uninstaller_args: [/Q],
            starter: derunner.start.bat,
            stoper: derunner.stop.bat,
            status: derunner.status.bat
        },
        lin: {
            version: 0.0.0,
            commit: a7d531b3431e6bc143a9b95d1019049354a9da9a,
            project_dir: Desota/DeRunner,
            execs_path: executables/Linux,
            setup: derunner.setup.bash,
            setup_args: [-m],
            uninstaller: derunner.uninstall.bash,
            uninstaller_args: [-q],
            starter: derunner.start.bash,
            stoper: derunner.stop.bash,
            status: derunner.status.bash,
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/DeRunner,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status:
        },
        service_type: asset,
        required: true,
        source_code: https://github.com/desotaai/derunner,
        report_issue: https://github.com/desotaai/derunner/issues,
        description: https://github.com/desotaai/derunner/tree/main#readme,
        short_description: Desota Client for API Requests,
        run_constantly: true,
        submodel: false
    },
    desotaai/tinypython: {
        win: {
            version: 0.0.0,
            commit: 22a3ffeb2d9c2c211847b18e1788abfe21aff58d,
            project_dir: Desota\Portables\TinyPython,
            execs_path: executables\Windows,
            setup: tinypython.setup.bat,
            setup_args: null,
            uninstaller: tinypython.uninstall.bat,
            uninstaller_args: [/Q],
            starter: ,
            stoper: ,
            status: ,
            python_path: Desota\Portables\TinyPython\env\python.exe
        },
        lin: {
            version: 0.0.0,
            commit: 22a3ffeb2d9c2c211847b18e1788abfe21aff58d,
            project_dir: Desota/Portables/TinyPython,
            execs_path: executables/Linux,
            setup: tinypython.setup.bash,
            setup_args: null,
            uninstaller: tinypython.uninstall.bash,
            uninstaller_args: [-q],
            starter: ,
            stoper: ,
            status: ,
            python_path: Desota/Portables/TinyPython/env/bin/python3
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/Portables/TinyPython,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status: ,
            python_path:
        },
        service_type: asset,
        required: true,
        source_code: https://github.com/DeSOTAai/TinyPython,
        report_issue: https://github.com/DeSOTAai/TinyPython/issues,
        description: https://github.com/DeSOTAai/TinyPython/tree/main#readme,
        short_description: Portable Python as tool for Dedicated Model Runners,
        run_constantly: false,
        submodel: false,
        child_models: 
    },
    # Models
    franciscomvargas/neuralqa/qa: {
        win: {
            version: 0.0.0,
            commit: 905edfc77f551ca6dad3327d1b74a46d9512a24f,
            install_dir: Desota\Desota_Models\NeuralQA, # OPTIONAL - `project_dir`as default 
            project_dir: Desota\Desota_Models\NeuralQA\neuralqa,
            execs_path: executables\Windows,
            setup: neuralqa.setup.bat,
            setup_args: [/manualstart],
            uninstaller: neuralqa.uninstall.bat,
            uninstaller_args: [/Q],
            starter: neuralqa.start.bat,
            stoper: neuralqa.stop.bat,
            status: neuralqa.status.bat,

            desota_runner: qa_runner.py,
            python_path: Desota\Desota_Models\NeuralQA\neuralqa\env\python.exe
        },
        lin: {
            version: 0.0.0,
            commit: 905edfc77f551ca6dad3327d1b74a46d9512a24f,
            project_dir: Desota/Desota_Models/NeuraQA/neuralqa,
            execs_path: executables/Linux,
            setup: neuralqa.setup.bash,
            setup_args: [-m],
            uninstaller: neuralqa.uninstall.bash,
            uninstaller_args: [-q],
            starter: neuralqa.start.bash,
            stoper: neuralqa.stop.bash,
            status: neuralqa.status.bash,

            desota_runner: qa_runner.py,
            python_path: Desota/Desota_Models/NeuraQA/neuralqa/env/bin/python3
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/Desota_Models/NeuraQA/neuralqa,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status: ,

            desota_runner: ,
            python_path:
        },
        service_type: model,
        timeout: 600,
        required: false,
        source_code: https://github.com/franciscomvargas/neuralqa,
        report_issue: https://github.com/franciscomvargas/neuralqa/issues,
        description: https://github.com/franciscomvargas/neuralqa/tree/master#readme,
        short_description: Library for Question Answering on Large Datasets with BERT,
        model_ui: http://127.0.0.1:8888/,
        handshake_req: http://127.0.0.1:8888/api/handshake/,
        handshake_res: {
            status: ready
        },
        run_constantly: false,
        submodel: false,
        child_models: [
            franciscomvargas/neuralqa/expansion
        ]
    },
    franciscomvargas/neuralqa/expansion: {
        win: {
            project_dir: Desota\Desota_Models\NeuralQA\neuralqa,
            desota_runner: expansion_runner.py,
            python_path: Desota\Desota_Models\NeuralQA\neuralqa\env\python.exe,

            
            runner: Desota\Desota_Models\NeuralQA\neuralqa\expansion_runner.py,
            runner_py: Desota\Desota_Models\NeuralQA\neuralqa\env\python.exe
        },
        lin: {
            project_dir: Desota/Desota_Models/NeuraQA/neuralqa,
            desota_runner: expansion_runner.py,
            python_path: Desota/Desota_Models/NeuraQA/neuralqa/env/bin/python3
        },
        mac: {
            project_dir: ,
            desota_runner: ,
            python_path:
        },
        service_type: model,
        timeout: 600,
        submodel: true,
        parent_model: franciscomvargas/neuralqa/qa
    },
    franciscomvargas/descraper/url: {
        win: {
            version: 0.0.0,
            commit: 2f27ff0d76f97ada3a2e46f0b875be5c640b81d6,
            project_dir: Desota\Desota_Models\DeScraper,
            execs_path: executables\Windows,
            setup: descraper.setup.bat,
            setup_args: [/manualstart],
            uninstaller: descraper.uninstall.bat,
            uninstaller_args: [/Q],
            starter: descraper.start.bat,
            stoper: descraper.stop.bat,
            status: descraper.status.bat,
            
            desota_runner: url_runner.py,
            python_path: Desota\Desota_Models\DeScraper\env\python.exe
        },
        lin: {
            version: 0.0.0,
            commit: 2f27ff0d76f97ada3a2e46f0b875be5c640b81d6,
            project_dir: Desota/Desota_Models/DeScraper,
            execs_path: executables/Linux,
            setup: descraper.setup.bash,
            setup_args: [-m],
            uninstaller: descraper.uninstall.bash,
            uninstaller_args: [-q],
            starter: descraper.start.bash,
            stoper: descraper.stop.bash,
            status: descraper.status.bash,
            
            desota_runner: url_runner.py,
            python_path: Desota/Desota_Models/DeScraper/env/bin/python3
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/Desota_Models/DeScraper,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status: ,

            desota_runner: ,
            python_path:
        },
        service_type: model,
        timeout: 600,
        required: false,
        source_code: https://github.com/franciscomvargas/descraper,
        report_issue: https://github.com/franciscomvargas/descraper/issues,
        description: https://github.com/franciscomvargas/descraper/tree/main#readme,
        short_description: WebScrape with assistance of AI Models,
        model_ui: http://127.0.0.1:8880/,
        handshake_req: http://127.0.0.1:8880/api/handshake/,
        handshake_res: {
            status: ready
        },
        run_constantly: true,
        submodel: false,
        child_models: [
            franciscomvargas/descraper/html
        ]
    },
    franciscomvargas/descraper/html: {
        win: {
            project_dir: Desota\Desota_Models\DeScraper,
            desota_runner: html_runner.py,
            python_path: Desota\Desota_Models\DeScraper\env\python.exe
        },
        lin: {
            project_dir: Desota/Desota_Models/DeScraper,
            desota_runner: html_runner.py,
            python_path: Desota/Desota_Models/DeScraper/env/bin/python3
        },
        mac: {
            project_dir: ,
            desota_runner: ,
            python_path:
        },
        service_type: model,
        timeout: 600,
        submodel: true,
        parent_model: franciscomvargas/descraper/url
    },
    franciscomvargas/whisper.cpp: {
        win: {
            version: ,
            commit: ,
            project_dir: Desota\Desota_Models\WhisperCpp,
            execs_path: executables\Windows,
            setup: whisper_cpp.setup.bat,
            setup_args: [/manualstart],
            uninstaller: whisper_cpp.uninstall.bat,
            uninstaller_args: [/Q],
            starter: ,
            stoper: ,
            status: ,

            desota_runner: runner.py,
            python_path: Desota\Portables\TinyPython\env\python.exe,
            cli_cmd: []
        },
        lin: {
            version: 0.0.0,
            commit: 354321d4f25bb91a7e03f40295fc8920c397d24a,
            project_dir: Desota/Desota_Models/WhisperCpp,
            execs_path: executables/Linux,
            setup: whisper_cpp.setup.bash,
            setup_args: [-m],
            uninstaller: whisper_cpp.uninstall.bash,
            uninstaller_args: [-q],
            starter: ,
            stoper: ,
            status: ,

            desota_runner: runner.py,
            python_path: Desota/Portables/TinyPython/env/bin/python3,
            cli_cmd: [
                Desota/Desota_Models/WhisperCpp/stream, 
                -m, Desota/Desota_Models/WhisperCpp/models/ggml-base.en.bin,
                --step, 30000,
                --length, 30000
            ]
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/Desota_Models/WhisperCpp,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status: ,

            desota_runner: ,
            python_path: ,
            cli_cmd: 
        },
        service_type: model,
        timeout: 600,
        required: false,
        source_code: https://github.com/franciscomvargas/whisper.cpp,
        report_issue: https://github.com/franciscomvargas/whisper.cpp/issues,
        description: https://github.com/franciscomvargas/whisper.cpp/tree/master#readme,
        short_description: Port of OpenAI's Whisper model in C/C++,
        model_cli: cli_cmd,
        run_constantly: false,
        submodel: false,
        child_models: null
    },
    # Tools
    franciscomvargas/deurlcruncher: {
        win: {
            version: 0.0.0,
            commit: 05abb8c43dd4b5f16d05584e926dc269a78e3972,
            project_dir: Desota\Desota_Models\DeUrlCruncher,
            execs_path: executables\Windows,
            setup: deurlcruncher.setup.bat,
            setup_args: [/manualstart],
            uninstaller: deurlcruncher.uninstall.bat,
            uninstaller_args: [/Q],
            starter: ,
            stoper: ,
            status: ,

            desota_runner: runner.py,
            python_path: Desota\Desota_Models\DeUrlCruncher\env\python.exe,
            cli_cmd: [
                Desota\Desota_Models\DeUrlCruncher\env\python.exe,
                Desota\Desota_Models\DeUrlCruncher\main.py
            ]
        },
        lin: {
            version: 0.0.0,
            commit: 05abb8c43dd4b5f16d05584e926dc269a78e3972,
            project_dir: Desota/Desota_Models/DeUrlCruncher,
            execs_path: executables/Linux,
            setup: deurlcruncher.setup.bash,
            setup_args: [-m],
            uninstaller: deurlcruncher.uninstall.bash,
            uninstaller_args: [-q],
            starter: ,
            stoper: ,
            status: ,

            desota_runner: runner.py,
            python_path: Desota/Desota_Models/DeUrlCruncher/env/bin/python3,
            cli_cmd: [
                Desota/Desota_Models/DeUrlCruncher/env/bin/python3,
                Desota/Desota_Models/DeUrlCruncher/main.py
            ]
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/Desota_Models/DeUrlCruncher,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status: ,

            desota_runner: ,
            python_path: ,
            cli_cmd: 
        },
        service_type: tool,
        timeout: 600,
        required: false,
        source_code: https://github.com/franciscomvargas/DeUrlCruncher,
        report_issue: https://github.com/franciscomvargas/DeUrlCruncher/issues,
        description: https://github.com/franciscomvargas/DeUrlCruncher/tree/main#readme,
        short_description: Get google URL results from string query,
        model_cli: cli_cmd,
        run_constantly: false,
        submodel: false,
        child_models: null
    }
}

## DeSOTA Manager Tools Params
manager_params: {
    win: {
        version: 0.2.0,
        project_dir: Desota\Desota_Models\DeManagerTools,
        build_url: https://github.com/DeSOTAai/DeManagerTools/releases/download/v0.1.1/v0.1.1-win64.zip,
        release_desc: Alpha Release > DeSOTA API Comunication
    },
    lin: {
        version: 0.2.0,
        project_dir: Desota/Desota_Models/DeManagerTools,
        build_url: https://github.com/DeSOTAai/DeManagerTools/releases/download/v0.1.1/v0.1.1-lin64.zip,
        release_desc: Alpha Release > DeSOTA API Comunication
    },
    mac: {
        version: ,
        project_dir: Desota/Desota_Models/DeManagerTools,
        build_url: ,
        release_desc: 
    },
    source_code: https://github.com/desotaai/demanagertools,
    report_issue: https://github.com/desotaai/demanagertools/issues,
    description: https://github.com/desotaai/demanagertools/tree/main#readme,
    short_description: DeSOTA Manager and Tools for Client Servers,
}
