#param: Get to know if all Services Status, inclusively if running in derunner
#type: dict{ str(model): int(status) } -> status ( 0=STOPPED | 1=STARTED | 2=RUNNING )
services_status: null

## DeSOTA Services Params
services_params: {
    # DeSOTA models runner
    desotaai/derunner: {
        win: {
            version: 1.0.0,
            commit: 9a3a6b97821e228c293b0d9f19c98cc30aa0f9e2,
            project_dir: Desota\DeRunner,
            execs_path: executables\Windows,
            setup: derunner.setup.bat,
            setup_args: [/manualstart],
            uninstaller: derunner.uninstall.bat,
            uninstaller_args: [/Q],
            starter: derunner.start.bat,
            stoper: derunner.stop.bat,
            status: derunner.status.bat,

            
            service_path: Desota\DeRunner\executables\Windows,
            installer: https://raw.githubusercontent.com/DeSOTAai/DeRunner/main/Executables/Windows/DeRunner.install.bat,
            installer_args: [/reinstall]
        },
        lin: {
            version: 0.0.0,
            commit: 9a3a6b97821e228c293b0d9f19c98cc30aa0f9e2,
            project_dir: Desota/DeRunner,
            execs_path: executables/Linux,
            setup: derunner.setup.bash,
            setup_args: [-m],
            uninstaller: derunner.uninstall.bash,
            uninstaller_args: [-q],
            starter: derunner.start.bash,
            stoper: derunner.stop.bash,
            status: derunner.status.bash,
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/DeRunner,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status:
        },
        source_code: https://github.com/desotaai/derunner,
        report_issue: https://github.com/desotaai/derunner/issues,
        description: https://github.com/desotaai/derunner/blob/main/README.md,
        short_description: Desota Client for API Requests,
        run_constantly: true,
        submodel: false
    },
    # Models
    franciscomvargas/neuralqa/qa: {
        win: {
            version: 1.0.1,
            commit: 905edfc77f551ca6dad3327d1b74a46d9512a24f,
            install_dir: Desota\Desota_Models\NeuralQA, # OPTIONAL - `project_dir`as default 
            project_dir: Desota\Desota_Models\NeuralQA\neuralqa,
            execs_path: executables\Windows,
            setup: neuralqa.setup.bat,
            setup_args: [/manualstart],
            uninstaller: neuralqa.uninstall.bat,
            uninstaller_args: [/Q],
            starter: neuralqa.start.bat,
            stoper: neuralqa.stop.bat,
            status: neuralqa.status.bat,

            desota_runner: qa_runner.py,
            python_path: Desota\Desota_Models\NeuralQA\neuralqa\env\python.exe,


            service_path: Desota\Desota_Models\NeuralQA\neuralqa\executables\Windows,
            installer: https://raw.githubusercontent.com/franciscomvargas/neuralqa/master/neuralqa/executables/Windows/neuralqa.install.bat,
            installer_args: [/reinstall],
            runner: Desota\Desota_Models\NeuralQA\neuralqa\qa_runner.py,
            runner_py: Desota\Desota_Models\NeuralQA\neuralqa\env\python.exe
        },
        lin: {
            version: 0.0.0,
            commit: 905edfc77f551ca6dad3327d1b74a46d9512a24f,
            project_dir: Desota/Desota_Models/NeuraQA/neuralqa,
            execs_path: executables/Linux,
            setup: neuralqa.setup.bash,
            setup_args: [-m],
            uninstaller: neuralqa.uninstall.bash,
            uninstaller_args: [-q],
            starter: neuralqa.start.bash,
            stoper: neuralqa.stop.bash,
            status: neuralqa.status.bash,

            desota_runner: qa_runner.py,
            python_path: Desota/Desota_Models/NeuraQA/neuralqa/env/bin/python3
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/Desota_Models/NeuraQA/neuralqa,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status: ,

            desota_runner: ,
            python_path:
        },
        source_code: https://github.com/franciscomvargas/neuralqa,
        report_issue: https://github.com/franciscomvargas/neuralqa/issues,
        description: https://github.com/franciscomvargas/neuralqa/blob/master/README_original.md,
        short_description: Library for Question Answering on Large Datasets with BERT,
        model_ui: http://127.0.0.1:8888/,
        handshake_req: http://127.0.0.1:8888/api/handshake/,
        handshake_res: {
            status: ready
        },
        run_constantly: false,
        submodel: false,
        child_models: [
            franciscomvargas/neuralqa/expansion
        ]
    },
    franciscomvargas/neuralqa/expansion: {
        win: {
            project_dir: Desota\Desota_Models\NeuralQA\neuralqa,
            desota_runner: expansion_runner.py,
            python_path: Desota\Desota_Models\NeuralQA\neuralqa\env\python.exe,

            
            runner: Desota\Desota_Models\NeuralQA\neuralqa\expansion_runner.py,
            runner_py: Desota\Desota_Models\NeuralQA\neuralqa\env\python.exe
        },
        lin: {
            project_dir: Desota/Desota_Models/NeuraQA/neuralqa,
            desota_runner: expansion_runner.py,
            python_path: Desota/Desota_Models/NeuraQA/neuralqa/env/bin/python3
        },
        mac: {
            project_dir: ,
            desota_runner: ,
            python_path:
        },
        submodel: true,
        parent_model: franciscomvargas/neuralqa/qa
    },
    franciscomvargas/descraper/url: {
        win: {
            version: 1.0.0,
            commit: 5e88a0ab690b8c2bf7682f80883d11c9af9c9ace,
            project_dir: Desota\Desota_Models\DeScraper,
            execs_path: executables\Windows,
            setup: descraper.setup.bat,
            setup_args: [/manualstart],
            uninstaller: descraper.uninstall.bat,
            uninstaller_args: [/Q],
            starter: descraper.start.bat,
            stoper: descraper.stop.bat,
            status: descraper.status.bat,
            
            desota_runner: url_runner.py,
            python_path: Desota\Desota_Models\DeScraper\env\python.exe,
            
            service_path: Desota\Desota_Models\DeScraper\executables\Windows,
            installer: https://raw.githubusercontent.com/franciscomvargas/descraper/main/executables/Windows/descraper.install.bat,
            installer_args: [/reinstall],
            runner: Desota\Desota_Models\DeScraper\url_runner.py,
            runner_py: Desota\Desota_Models\DeScraper\env\python.exe,
        },
        lin: {
            version: 0.0.0,
            commit: 5e88a0ab690b8c2bf7682f80883d11c9af9c9ace,
            project_dir: Desota/Desota_Models/DeScraper,
            execs_path: executables/Linux,
            setup: descraper.setup.bash,
            setup_args: [-m],
            uninstaller: descraper.uninstall.bash,
            uninstaller_args: [-q],
            starter: descraper.start.bash,
            stoper: descraper.stop.bash,
            status: descraper.status.bash,
            
            desota_runner: url_runner.py,
            python_path: Desota/Desota_Models/DeScraper/env/bin/python3
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/Desota_Models/DeScraper,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status: ,

            desota_runner: ,
            python_path:
        },
        source_code: https://github.com/franciscomvargas/descraper,
        report_issue: https://github.com/franciscomvargas/descraper/issues,
        description: https://github.com/franciscomvargas/descraper/blob/main/README.md,
        short_description: WebScrape with assistance of AI Models,
        model_ui: http://127.0.0.1:8880/,
        handshake_req: http://127.0.0.1:8880/api/handshake/,
        handshake_res: {
            status: ready
        },
        run_constantly: true,
        submodel: false,
        child_models: [
            franciscomvargas/descraper/html
        ]
    },
    franciscomvargas/descraper/html: {
        win: {
            project_dir: Desota\Desota_Models\DeScraper,
            desota_runner: html_runner.py,
            python_path: Desota\Desota_Models\DeScraper\env\python.exe,
        },
        lin: {
            project_dir: Desota/Desota_Models/DeScraper,
            desota_runner: html_runner.py,
            python_path: Desota/Desota_Models/DeScraper/env/bin/python3
        },
        mac: {
            project_dir: ,
            desota_runner: ,
            python_path:
        },
        submodel: true,
        parent_model: franciscomvargas/descraper/url
    },
    franciscomvargas/deurlcruncher: {
        win: {
            version: 1.0.1,
            commit: 0d670e8f766b6c7e7b0ea3e7f56dc489d01a56ce,
            project_dir: Desota\Desota_Models\DeUrlCruncher,
            execs_path: executables\Windows,
            setup: deurlcruncher.setup.bat,
            setup_args: [/manualstart],
            uninstaller: deurlcruncher.uninstall.bat,
            uninstaller_args: [/Q],
            starter: ,
            stoper: ,
            status: ,

            desota_runner: runner.py,
            python_path: Desota\Desota_Models\DeUrlCruncher\env\python.exe,
            cli_cmd: [
                Desota\Desota_Models\DeUrlCruncher\env\python.exe,
                Desota\Desota_Models\DeUrlCruncher\main.py
            ],

            service_path: Desota\Desota_Models\DeUrlCruncher\executables\Windows,
            installer: https://raw.githubusercontent.com/franciscomvargas/DeUrlCruncher/main/executables/Windows/deurlcruncher.install.bat,
            installer_args: [/reinstall],
            runner: Desota\Desota_Models\DeUrlCruncher\runner.py,
            runner_py: Desota\Desota_Models\DeUrlCruncher\env\python.exe,
        },
        lin: {
            version: 0.0.0,
            commit: 0d670e8f766b6c7e7b0ea3e7f56dc489d01a56ce,
            project_dir: Desota/Desota_Models/DeUrlCruncher,
            execs_path: executables/Linux,
            setup: deurlcruncher.setup.bash,
            setup_args: [-m],
            uninstaller: deurlcruncher.uninstall.bash,
            uninstaller_args: [-q],
            starter: ,
            stoper: ,
            status: ,

            desota_runner: runner.py,
            python_path: Desota/Desota_Models/DeUrlCruncher/env/bin/python3,
            cli_cmd: [
                Desota/Desota_Models/DeUrlCruncher/env/bin/python3,
                Desota/Desota_Models/DeUrlCruncher/main.py
            ]
        },
        mac: {
            version: ,
            commit: ,
            project_dir: Desota/Desota_Models/DeUrlCruncher,
            execs_path: executables/MacOS,
            setup: ,
            setup_args: ,
            uninstaller: ,
            uninstaller_args: ,
            starter: ,
            stoper: ,
            status: ,

            desota_runner: ,
            python_path:
        },
        source_code: https://github.com/franciscomvargas/DeUrlCruncher,
        report_issue: https://github.com/franciscomvargas/DeUrlCruncher/issues,
        description: https://github.com/franciscomvargas/DeUrlCruncher/blob/main/README.md,
        short_description: Get google URL results from string query,
        model_ui: ,
        model_cli: cli_cmd,
        handshake_req: ,
        handshake_res: ,
        run_constantly: false,
        submodel: false,
        child_models:
    },
}

## DeSOTA Manager Tools Params
### TODO - Install > Setup Upgrade
manager_params: {
    win: {
        version: 0.0.2,
        project_dir: Desota\Desota_Models\DeManagerTools,
        build_url: https://github.com/DeSOTAai/DeManagerTools/releases/download/v0.0.2/v0.0.2-win64.zip,
        release_desc: Upgrade with DeRunner Logs in DeManagerTools Dashboard (DeSOTA Requests)
    },
    lin: {
        version: 0.0.3,
        project_dir: Desota/Desota_Models/DeManagerTools,
        build_url: https://github.com/DeSOTAai/DeManagerTools/releases/download/v0.0.2/v0.0.3-lin64.zip,
        release_desc: pre-release
    },
    mac: {
        version: 1.0.0,
        project_dir: Desota/Desota_Models/DeManagerTools,
        build_url: ,
        release_desc: 
    },
    source_code: https://github.com/desotaai/demanagertools,
    report_issue: https://github.com/desotaai/demanagertools/issues,
    description: https://github.com/desotaai/demanagertools/blob/main/README.md,
    short_description: DeSOTA Manager and Tools for Client Servers,
}
